baseurl = "http://www.grapehut.xyz/me"
title = "å°é¥…é ­ã®éƒ¨å±‹"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
#style = "monokai"
style = "github-light"

[params]
  author = "å°é¥…é ­ã®éƒ¨å±‹"
  info = "Stay hungry. Stay foolish. --Steve Jobs"
  description = "å°é¥…é ­ã®éƒ¨å±‹"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  #gravatar = "test@test.com"

  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2024
  license= "<a href='https://icp.gov.moe/?keyword=20241189' target='_blank'>èŒICPå¤‡20241189å·</a>"

  enableTwemoji = true
  colorScheme = "auto"  #"auto" or "light" or "dark"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css","css/APlayer.min.css"]
  customJS = ["js/sakuraPlus.js","js/APlayer.min.js"]
  customRemoteJS= ["<script async src='https://cdn.seline.so/seline.js' data-token='5b15b5092d4879e'></script>","<script async src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9661896697976587' crossorigin='anonymous'></script>"]

  enableMusic = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Social links
[[params.social]]
  name = "å°é¥…é ­ã®éƒ¨è½æ ¼â„¬"
  icon = "fa-solid fa-pen-to-square fa-3x"
  weight = 1
  url = "https://www.grapehut.xyz"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®éŸ³æ¥½â™ª"
  icon = "fa-solid fa-headphones fa-3x"
  weight = 2
  url = "https://www.mureka.ai/home"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®å®¶åº­å½±é™¢ğŸ"
  icon = "fa-solid fa-film fa-3x"
  weight = 3
  url = "https://libretv.laosiji123.dpdns.org/"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®ç”µè§†ç›´æ’­ğŸ“º"
  icon = "fa-brands fa-chromecast fa-3x"
  weight = 4
  url = "https://iptv.grapehut.dpdns.org/"
  target = "_blank"
  
[[params.social]]
  name = "å°é¥…é ­ã®æ”¶è—å¤¹ğŸ”–"
  icon = "fa-solid fa-list fa-3x"
  weight = 5
  url = "https://webstack.grapehut.dpdns.org/"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®èŒå¨˜Live2DğŸ±"
  icon = "fa-solid fa-venus fa-3x"
  weight = 6
  url = "https://live2d-widget.grapehut.dpdns.org/"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®èŒå¨˜Live2D-Cubism3ğŸ¶"
  icon = "fa-solid fa-venus-double fa-3x"
  weight = 7
  url = "https://live2d-cubism3.grapehut.dpdns.org/"
  target = "_blank"
  
[[params.social]]
  name = "å°é¥…é ­ã®å­—ä½“ç”„é€‰âœ"
  icon = "fa-solid fa-signature fa-3x"
  weight = 8
  url = "https://myfont.dpdns.org"
  target = "_blank"  

[[params.social]]
  name = "mirai-tech ãŠ‘"
  icon = "fa-solid fa-earth-americas fa-3x"
  weight = 9
  url = "https://mirai-tech.dpdns.org/"
  target = "_blank"
  
[[params.social]]
  name = "å°é¥…é ­ã®è¯­éŸ³å…‹éš†tts"
  icon = "fa-solid fa-microphone fa-3x"
  weight = 80
  url = "https://libretts-4l5.pages.dev/"
  target = "_blank"  

[[params.social]]
  name = "å°é¥…é ­ã®n8n â˜¯"
  icon = "fa-brands fa-hubspot fa-3x"
  weight = 81
  url = "https://n8n-tqjzivfe.ap-northeast-1.clawcloudrun.com/"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®ç§˜å¯†åŸºåœ° â˜£"
  icon = "fa-regular fa-eye-slash fa-3x"
  weight = 90
  url = "https://"
  target = "_blank"

[[params.social]]
  name = "å°é¥…é ­ã®ç½‘ç«™ç›‘æ§ğŸ‘“"
  icon = "fa-solid fa-chart-bar fa-3x"
  weight = 99
  url = "https://klrbsexb.ap-northeast-1.clawcloudrun.com/status/gg"
  target = "_blank"


# Menu links
[menu]
[[menu.main]]
  name = "Line"
  pre = "fa-brands fa-line fa-2x"
  weight = 1
  url = "https://access.line.me/oauth2/v2.1/login?fromDomain=access-auto.line.me&loginState=nBeMaOY7Mdu5aFeSo1hVfn&line_auto_login_error=universal_link_error&loginChannelId=1445834080&returnUri=oauth2v2.1authorizeconsentbot_promptnormalscopeopenidprofileresponse_typecodestateRhiVgBoLDGredirect_urihttps3A2F2Fform.tonariwa.com2Fsuntory2Fmeasure_url3Fcpid3Dtennensui_sampling426lcd3D126type3D126nonceEvutxGZ894client_id1445834080"

[[menu.main]]
  name = "Wechat"
  pre = "fa-brands fa-weixin fa-2x"
  weight = 2
  url = "https://web.wechat.com/uklccp?lang=en_US&t=v2/index"

[[menu.main]]
  name = "Telegram"
  pre = "fa-brands fa-telegram fa-2x"
  weight = 3
  url = "https://web.telegram.org/"

[[menu.main]]
  name = "Youtube"
  pre = "fa-brands fa-youtube fa-2x"
  weight = 4
  url = "https://youtube.com/"

[[menu.main]]
  name = "Bilibili"
  pre = "fa-brands fa-bilibili fa-2x"
  weight = 5
  url = "https://bilibili.com/"

[[menu.main]]
  name = "Tiktok"
  pre = "fa-brands fa-tiktok fa-2x"
  weight = 6
  url = "https://tiktok.com/"

[[menu.main]]
  name = "ãƒ‹ã‚³ãƒ‹ã‚³å‹•ç”»"
  pre = "fa-solid fa-tv fa-2x"
  weight = 7
  url = "https://nicovideo.jp/"
